const fs = require('fs');
let content = fs.readFileSync('components/dashboard/AIExerciseGeneratorScreen.tsx', 'utf8');

// Add autoGenerate to props
content = content.replace(
  /initialSetId\?: string \| null;/,
  `initialSetId?: string | null;\n  autoGenerate?: boolean;`
);

content = content.replace(
  /const AIExerciseGeneratorScreen: React\.FC<AIExerciseGeneratorScreenProps> = \(\{ initialSetId = null,/,
  `const AIExerciseGeneratorScreen: React.FC<AIExerciseGeneratorScreenProps> = ({ initialSetId = null, autoGenerate = false,`
);

// Add useEffect to trigger handleGenerateExercises
const effectCode = `
  useEffect(() => {
    if (initialSetId) {
      setSelectedSetId(initialSetId);
      if (initialSetId.startsWith('lesson_') || initialSetId.startsWith('vocab-')) {
        const cleanId = initialSetId.replace(/^(lesson_|vocab-|set-)/, '');
        setSelectedLessonIds([cleanId]);
      }
    }
  }, [initialSetId]);

  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  useEffect(() => {
    if (autoGenerate && !hasAutoGenerated && selectedSetId) {
       // Wait a tiny bit for states to settle
       setTimeout(() => {
          handleGenerateExercises();
          setHasAutoGenerated(true);
       }, 100);
    }
  }, [autoGenerate, hasAutoGenerated, selectedSetId]);
`;

content = content.replace(
  /useEffect\(\(\) => \{\s*if \(initialSetId\) \{\s*setSelectedSetId\(initialSetId\);\s*if \(initialSetId\.startsWith[\s\S]*?\}\s*\}\s*\}, \[initialSetId\]\);/,
  effectCode
);

fs.writeFileSync('components/dashboard/AIExerciseGeneratorScreen.tsx', content);
