import { Slide, SlideElement } from '../types/presentation';
import { getAI, extractJSON } from './geminiService';

export interface GeneratePresentationFromNotesParams {
  notes: string;
  topic?: string;
  level?: string;
  slideCount?: number;
  onProgress?: (step: 'creator' | 'reviewer' | 'done', message: string) => void;
}

/**
 * Silnik AI do generowania slajdów — narada modeli w 100% oparta na Google Gemini (dwuetapowy pipeline):
 * 1. Krok 1 (Twórca): wywołanie gemini-3.8-flash z thinkingLevel: 'low'. Analizuje materiał i tworzy 3-6 slajdów w JSON.
 * 2. Krok 2 (Recenzent): osobne wywołanie gemini-3.8-flash weryfikujące zwięzłość treści (zasada max 5 punktów, poprawność językowa, naturalność fraz).
 */
export async function generatePresentationWithGeminiDualPass({
  notes,
  topic = 'General English Conversation',
  level = 'B2',
  slideCount = 4,
  onProgress,
}: GeneratePresentationFromNotesParams): Promise<Slide[]> {
  const ai = getAI();

  // -------------------------------------------------------------
  // KROK 1: TWÓRCA (gemini-3.8-flash z parametrem thinkingLevel: 'low')
  // -------------------------------------------------------------
  onProgress?.('creator', 'Krok 1/2: Twórca (Gemini 3.8 Flash) analizuje materiał i buduje slajdy...');

  const creatorSystemInstruction = `You are an expert English teacher presentation designer. 
Analyze the provided teaching notes/materials and generate an interactive ${slideCount}-slide lesson deck for level ${level}.
Topic: "${topic}".

SLIDE STRUCTURE:
Each slide must have:
- title: Short, engaging title in English
- notes: Detailed teacher speaker notes (pedagogical tips, target questions)
- layoutTemplate: One of 'title_points', 'dialogue', 'vocabulary', 'image_exercise'
- elements: Array of slide elements with:
  * id: unique string
  * type: 'text' | 'vocabulary' | 'exercise'
  * content: clean text or markdown points
  * position: { x: number, y: number } (percentages 0-100)
  * style: optional styling (fontSize, fontWeight, textAlign)
  * vocabularyData: if type is 'vocabulary', array of { term, translation, example }
  * exerciseData: if type is 'exercise', { instruction, prompt, answer }

Return valid JSON with key "slides": [...]`;

  const creatorPrompt = `Here are the lesson notes and input material:
---
${notes.trim()}
---
Generate between 3 and ${Math.max(3, Math.min(6, slideCount))} structured, pedagogically sound slides.`;

  const creatorResponse = await ai.models.generateContent({
    model: 'gemini-3.8-flash',
    contents: creatorPrompt,
    config: {
      systemInstruction: creatorSystemInstruction,
      responseMimeType: 'application/json',
      thinkingConfig: {
        thinkingLevel: 'low'
      }
    }
  });

  const creatorRaw = creatorResponse?.text || '';
  let draftSlides: Slide[] = [];
  try {
    const parsed = JSON.parse(extractJSON(creatorRaw));
    draftSlides = Array.isArray(parsed) ? parsed : (parsed.slides || []);
  } catch (err) {
    console.error('[Gemini DualPass] Błąd parsowania wyjścia Twórcy:', err, creatorRaw);
    throw new Error('Twórca AI nie zwrócił poprawnego formatu slajdów.');
  }

  if (!draftSlides || draftSlides.length === 0) {
    throw new Error('Twórca AI wygenerował pustą listę slajdów.');
  }

  // -------------------------------------------------------------
  // KROK 2: RECENZENT (gemini-3.8-flash - weryfikacja zwięzłości i jakości)
  // -------------------------------------------------------------
  onProgress?.('reviewer', 'Krok 2/2: Recenzent (Gemini 3.8 Flash) sprawdza zwięzłość, naturalność i regułę max. 5 punktów...');

  const reviewerSystemInstruction = `You are a strict Head of English Academics and presentation editor.
Your task is to review and optimize a draft presentation generated for an English lesson.

CRITICAL RULES TO ENFORCE:
1. Conciseness (Rule of 5): Never allow more than 4-5 bullet points or concise lines per slide. Avoid walls of text.
2. Natural English Phrasing: Ensure modern, idiomatic British or American English without awkward translations.
3. Engaging Layouts: Ensure slide elements have logical (x, y) coordinates so they do not overlap on a 16:9 canvas.
4. Preserved Format: You must return the improved slides strictly adhering to the JSON schema with key "slides": [...].`;

  const reviewerPrompt = `Here is the draft slide deck generated by the creator model:
\`\`\`json
${JSON.stringify(draftSlides, null, 2)}
\`\`\`

Review and rewrite every slide to be punchy, clear, perfectly suited for a 16:9 slide, respecting max 5 points per slide. Return JSON with the key "slides".`;

  const reviewerResponse = await ai.models.generateContent({
    model: 'gemini-3.8-flash',
    contents: reviewerPrompt,
    config: {
      systemInstruction: reviewerSystemInstruction,
      responseMimeType: 'application/json',
      thinkingConfig: {
        thinkingLevel: 'low'
      }
    }
  });

  const reviewerRaw = reviewerResponse?.text || '';
  let finalSlides: Slide[] = [];
  try {
    const parsedReviewed = JSON.parse(extractJSON(reviewerRaw));
    finalSlides = Array.isArray(parsedReviewed) ? parsedReviewed : (parsedReviewed.slides || draftSlides);
  } catch (err) {
    console.warn('[Gemini DualPass] Recenzent zwrócił błąd parsowania JSON, powrót do wersji Twórcy:', err);
    finalSlides = draftSlides;
  }

  // Normalizacja identyfikatorów i domyślnych pozycji
  const sanitizedSlides: Slide[] = finalSlides.map((slide, sIdx) => ({
    id: slide.id || `slide-${Date.now()}-${sIdx}`,
    title: slide.title || `Slajd ${sIdx + 1}`,
    notes: slide.notes || '',
    layoutTemplate: slide.layoutTemplate || 'title_points',
    elements: (slide.elements || []).map((el, elIdx) => ({
      id: el.id || `el-${sIdx}-${elIdx}-${Date.now()}`,
      type: el.type || 'text',
      content: el.content || '',
      position: {
        x: typeof el.position?.x === 'number' ? Math.max(0, Math.min(90, el.position.x)) : 10,
        y: typeof el.position?.y === 'number' ? Math.max(0, Math.min(90, el.position.y)) : 20 + elIdx * 20,
      },
      style: el.style || {},
      vocabularyData: el.vocabularyData,
      exerciseData: el.exerciseData
    }))
  }));

  onProgress?.('done', 'Slajdy zostały pomyślnie wygenerowane i zweryfikowane!');
  return sanitizedSlides;
}
